version: '3.3'

services:
  # core
  waste-db-writer:
    image: wasteant/wasteant:waste-db-writer-service-ubuntu.20.04
    container_name: waste-db-writer-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    networks:
      - internal
      - edge_cloud_sync_internal
    ports:
      - ${INET_HTTP_SERVER_PORT}:${INET_HTTP_SERVER_PORT}
      - ${EVENT_API_PORT}:${EVENT_API_PORT}
      - ${DJANGO_ADMIN_PORT}:${DJANGO_ADMIN_PORT}
      - ${FLOWER_PORT}:${FLOWER_PORT}
      - ${DATA_API_PORT}:${DATA_API_PORT}
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/home/$user/src
    user: ${user}
    depends_on:
      - rabbitmq
      - postgres

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: waste-db-writer-rabbitmq
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_INTERFACE_PORT}:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:latest
    container_name: waste-db-writer-postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: wasteantadmin@2024
      POSTGRES_DB: waste_db
    networks:
     - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge 
  edge_cloud_sync_internal:
    external: true

volumes:
  postgres_data: