# Generated by Django 4.2 on 2024-09-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeBoxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_box_id', models.CharField(max_length=255)),
                ('edge_box_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'EdgeBox Information',
                'db_table': 'edge_box_info',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Information',
                'db_table': 'plant_info',
            },
        ),
        migrations.CreateModel(
            name='WasteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ack_status', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Waste Feedback',
                'verbose_name_plural': 'Waste Feedbacks',
                'db_table': 'waste_feedback',
            },
        ),
        migrations.CreateModel(
            name='WasteSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_uid', models.CharField(max_length=255)),
                ('event_uid', models.CharField(default=models.CharField(max_length=255), max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_tracker_id', models.IntegerField()),
                ('object_polygon', models.JSONField()),
                ('confidence_score', models.FloatField(max_length=100)),
                ('object_area', models.FloatField(max_length=100)),
                ('object_length', models.FloatField(max_length=100)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_file', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste Segments',
                'db_table': 'waste_segments',
            },
        ),
        migrations.CreateModel(
            name='WasteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uid', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_tracker_id', models.IntegerField()),
                ('object_material_type', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('img_id', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
                ('object_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments')),
            ],
            options={
                'verbose_name_plural': 'Waste Material',
                'db_table': 'waste_material',
            },
        ),
        migrations.CreateModel(
            name='WasteImpurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uid', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_tracker_id', models.IntegerField()),
                ('is_long', models.BooleanField(default=False)),
                ('is_problematic', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.IntegerField()),
                ('object_coordinates', models.JSONField(blank=True, null=True)),
                ('img_id', models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
                ('object_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments')),
            ],
            options={
                'verbose_name_plural': 'Waste Impurity',
                'db_table': 'waste_impurity',
            },
        ),
        migrations.CreateModel(
            name='WasteHotSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uid', models.CharField(max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.IntegerField()),
                ('img_id', models.CharField(max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste HotSpot',
                'db_table': 'waste_hostspot',
            },
        ),
        migrations.CreateModel(
            name='WasteDust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_uid', models.CharField(max_length=255)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.IntegerField()),
                ('img_id', models.CharField(max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste Dust',
                'db_table': 'waste_dust',
            },
        ),
        migrations.AddField(
            model_name='edgeboxinfo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantinfo'),
        ),
    ]
