# Generated by Django 4.2 on 2024-05-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeBoxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_box_id', models.CharField(max_length=255)),
                ('edge_box_location', models.CharField(max_length=255)),
                ('entry_timestamp', models.DateTimeField(max_length=255)),
                ('meta_info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'EdgeBox Information',
                'db_table': 'edge_box_info',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Plant Information',
                'db_table': 'plant_info',
            },
        ),
        migrations.CreateModel(
            name='WasteSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_uid', models.CharField(max_length=255)),
                ('object_tracker_id', models.IntegerField(max_length=100)),
                ('object_polygon', models.JSONField()),
                ('confidence_score', models.FloatField(max_length=100)),
                ('object_area', models.FloatField(max_length=100)),
                ('object_length', models.FloatField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste Segments',
                'db_table': 'waste_segments',
            },
        ),
        migrations.CreateModel(
            name='WasteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_uid', models.CharField(max_length=255)),
                ('object_tracker_id', models.IntegerField(max_length=100)),
                ('object_material_type', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste Material',
                'db_table': 'waste_material',
            },
        ),
        migrations.CreateModel(
            name='WasteImpurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_uid', models.CharField(max_length=255)),
                ('object_tracker_id', models.IntegerField(max_length=100)),
                ('is_long', models.BooleanField(default=False)),
                ('is_problematic', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Waste Impurity',
                'db_table': 'waste_impurity',
            },
        ),
        migrations.AddField(
            model_name='edgeboxinfo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantinfo'),
        ),
    ]
