# Generated by Django 4.2 on 2024-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteimpurity',
            name='object_tracker_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wastematerial',
            name='object_tracker_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wastesegments',
            name='object_tracker_id',
            field=models.IntegerField(),
        ),
    ]
