# Generated by Django 4.2 on 2024-05-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_wasteimpurity_object_tracker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeboxinfo',
            name='entry_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wasteimpurity',
            name='object_uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'),
        ),
        migrations.AlterField(
            model_name='wastematerial',
            name='object_uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'),
        ),
    ]
