# Generated by Django 4.2 on 2024-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_edgeboxinfo_entry_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastesegments',
            name='rgb_img_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='wastesegments',
            name='rgb_img_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
