# Generated by Django 4.2 on 2024-09-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_filter_filteritem_metadata_metadatacolumn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='item_value',
        ),
    ]
