# Generated by Django 4.2 on 2024-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_wastesegments_rgb_img_file_wastesegments_rgb_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeboxinfo',
            name='meta_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='meta_info',
            field=models.JSONField(),
        ),
    ]
