# Generated by Django 4.2 on 2024-09-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_wastealarm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filteritem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filteritem',
            name='filter',
        ),
        migrations.AlterUniqueTogether(
            name='filteritemlocalization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filteritemlocalization',
            name='filter_item',
        ),
        migrations.AlterUniqueTogether(
            name='filterlocalization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='filterlocalization',
            name='filter',
        ),
        migrations.AlterUniqueTogether(
            name='metadatacolumn',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadatacolumn',
            name='metadata',
        ),
        migrations.AlterUniqueTogether(
            name='metadatalocalization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadatalocalization',
            name='metadata_column',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='FilterItem',
        ),
        migrations.DeleteModel(
            name='FilterItemLocalization',
        ),
        migrations.DeleteModel(
            name='FilterLocalization',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.DeleteModel(
            name='MetadataColumn',
        ),
        migrations.DeleteModel(
            name='MetadataLocalization',
        ),
    ]
