# Generated by Django 4.2 on 2024-05-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_edgeboxinfo_meta_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfo',
            name='contact_info',
        ),
    ]
