# Generated by Django 4.2 on 2024-05-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_plantinfo_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastesegments',
            old_name='rgb_img_file',
            new_name='img_file',
        ),
        migrations.RenameField(
            model_name='wastesegments',
            old_name='rgb_img_id',
            new_name='img_id',
        ),
    ]
