# Generated by Django 4.2 on 2024-09-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_filteritem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastealarm',
            old_name='source',
            new_name='event',
        ),
    ]
