# Generated by Django 4.2 on 2024-05-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_rgb_img_file_wastesegments_img_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeboxinfo',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='plantinfo',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wasteimpurity',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wastematerial',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wastesegments',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
    ]
