# Generated by Django 4.2 on 2024-05-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='edgeboxinfo',
            options={'verbose_name_plural': 'EdgeBox Information'},
        ),
        migrations.AlterModelOptions(
            name='plantinfo',
            options={'verbose_name_plural': 'Plant Information'},
        ),
        migrations.AlterModelOptions(
            name='wasteimpurity',
            options={'verbose_name_plural': 'Waste Impurity'},
        ),
        migrations.AlterModelOptions(
            name='wastematerial',
            options={'verbose_name_plural': 'Waste Material'},
        ),
        migrations.AlterModelOptions(
            name='wastesegments',
            options={'verbose_name_plural': 'Waste Segments'},
        ),
    ]
