# Generated by Django 4.2 on 2024-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteimpurity',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastematerial',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastesegments',
            name='meta_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
