# Generated by Django 4.2 on 2024-06-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_wasteimpurity_meta_info_wastematerial_meta_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteHotSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.IntegerField()),
                ('img_id', models.CharField(max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
                ('event_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments')),
            ],
            options={
                'verbose_name_plural': 'Waste HotSpot',
                'db_table': 'waste_hostspot',
            },
        ),
        migrations.CreateModel(
            name='WasteDust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField()),
                ('severity_level', models.IntegerField()),
                ('img_id', models.CharField(max_length=255)),
                ('img_file', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_tag', models.CharField(max_length=255)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
                ('event_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments')),
            ],
            options={
                'verbose_name_plural': 'Waste Dust',
                'db_table': 'waste_dust',
            },
        ),
    ]
