# Generated by Django 4.2 on 2024-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_wastehotspot_wastedust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedust',
            name='event_uid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wastehotspot',
            name='event_uid',
            field=models.CharField(max_length=255),
        ),
    ]
