# Generated by Django 4.2 on 2024-06-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_wastedust_event_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ack_status', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Waste Feedback',
                'verbose_name_plural': 'Waste Feedbacks',
                'db_table': 'waste_feedback',
            },
        ),
        migrations.AddField(
            model_name='wastedust',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastehotspot',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wasteimpurity',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wasteimpurity',
            name='event_uid',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255),
        ),
        migrations.AddField(
            model_name='wastematerial',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastematerial',
            name='event_uid',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255),
        ),
    ]
