# Generated by Django 4.2 on 2024-06-26 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_wastefeedback_wastedust_delivery_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteimpurity',
            name='img_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteimpurity',
            name='img_id',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255),
        ),
        migrations.AddField(
            model_name='wastematerial',
            name='img_file',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastematerial',
            name='img_id',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.wastesegments'), max_length=255),
        ),
    ]
