# Generated by Django 4.2 on 2024-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_wasteimpurity_img_file_wasteimpurity_img_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteimpurity',
            name='severity_level',
            field=models.IntegerField(),
        ),
    ]
